### ISSUE TITLE
stopped reading sdge meter on 5/23

### ISSUE THREAD

**Issue by White-Goblin** [jrouvier/esphome-emporia-vue-utility#6]
my vue connect stopped getting meter reading responses from the meter on 5/23. logs show that it is still connected, and my sdge app says the device is still provisioned, but the logs show no meter response. the logs do show a response when the vue sends a join request. not sure if its a meter issue, or issue with the connect itself. posting here in case it's a widespread issue.

**Comment by White-Goblin** [comment]
a power cycle of the vue fixed the issue. if there's a way to post logs in case you want to investigate the cause let me know.

**Comment by jrouvier** [comment]
Best way to post logs would be in a comment here.

Closing as I assume it hasn't happened again probably just a random crash
